### PR TITLE
Order facets by count

### PR DESCRIPTION
**Pull request by jordanpadams**
## 🗒️ Summary
Order facets by count

Also removes boost filters

## ♻️ Related Issues

Refs NASA-PDS/portal-wp#69

### CODE REVIEW

**Comment by nutjob4life** [comment]
Asked to review but already merged 🤷

**Comment by nutjob4life** [comment]
@jordanpadams if you're going to submit a PR at 3:00pm PT and then merge at 3:08pm without any review, I have to ask: _what are we doing here?_ You have the permissions to commit directly to `main`—just do that and not waste anyone else's time, right?

**Comment by jordanpadams** [comment]
@nutjob4life I agree. I was in a rush to get these changes in for the weekend. This was bad form. I will roll back that changes and create a new PR for the changes as needed.

**Comment by nutjob4life** [comment]
@jordanpadams don't sweat it! Sometimes time is of the essence

**Pull request merged**
