### PR TITLE
Upgrades for improved page type handling and refined search boosting

### PR DESCRIPTION
**Pull request by jordanpadams**
## 🗒️ Summary
* [Update title to be single value](https://github.com/NASA-PDS/registry-legacy-solr/commit/124dd07c09e4ba53e6ae6a5a131f0fb25cf22b45)
* [Update page_type support to collapse down all Data](https://github.com/NASA-PDS/registry-legacy-solr/commit/8cdab3c0647db880d01dd0bdb9f193cf4e45ea37)
* page_type updated for Instrument Host to remove underscore
* Upgrade Harvest to no longer check for primary products

## ⚙️ Test Data and/or Report
See keyword search on staging for deployed version and pds-sit for use in new search

## ♻️ Related Issues

resolves https://github.com/NASA-PDS/registry-legacy-solr/issues/158
Resolves https://github.com/NASA-PDS/registry-legacy-solr/issues/168
Resolves https://github.com/NASA-PDS/registry-legacy-solr/issues/159
Resolves https://github.com/NASA-PDS/registry-legacy-solr/issues/174

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
Visual inspection: ✅
Maven tests: ✅
```console
$ git branch --show-current
search_upgrades
$ mvn clean test
…
[INFO] Reactor Summary for Legacy Registry 4.3.0-SNAPSHOT:
[INFO] 
[INFO] Legacy Registry .................................... SUCCESS [  0.293 s]
[INFO] Legacy Search Core ................................. SUCCESS [  4.944 s]
[INFO] Legacy Harvest Tool ................................ SUCCESS [  7.230 s]
[INFO] Legacy Catalog Tool ................................ SUCCESS [  2.648 s]
[INFO] Legacy Registry Manager Solr ....................... SUCCESS [  1.141 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
…
```

**Comment by jordanpadams** [comment]
@eddiesarevalo can we update the search on pds-sit to use this updated version deployed on the staging service to checkout if this is meeting your needs?

**Comment by eddiesarevalo** [comment]
@jordanpadams Sure! Is it the same endpoint as before or a pds-sit one? 
The one I'm currently developing the new facets UI is the one at https://pds.nasa.gov/services/search/search

**Comment by jordanpadams** [comment]
Per sprint review, this seems to be working well and is ready for merge.

**Pull request merged**
